<#
.SYNOPSIS
    Automates the setup and deployment of different Discord bot types
    using Docker, under the "Red-E Bot" suite.
.DESCRIPTION
    This script provides a menu to choose between:
    1. Red-DiscordBot (Python Framework)
    2. Node-RED (Visual Flow Platform)

    It checks for Docker, creates a dedicated directory for the instance
    under C:\DiscordBots, generates the required docker-compose.yml,
    and launches the container.
#>

# --- Function to Install Red-DiscordBot (Python) ---
function Install-RedBot {
    param (
        [string]$BasePath
    )

    Write-Host "`n--- 1. Installing Red-DiscordBot (Python Framework) ---"
    $BotInstanceName = Read-Host -Prompt "Enter a name for this bot instance (e.g., mybot). This will be the folder name."
    $ContainerName = Read-Host -Prompt "Enter a unique name for the Docker container (e.g., mybot-docker)"

    # --- Construct and Create Installation Path ---
    $InstallPath = Join-Path -Path $BasePath -ChildPath $BotInstanceName

    if (-not (Test-Path -Path $InstallPath)) {
        Write-Host "Creating installation directory: $InstallPath"
        try {
            New-Item -ItemType Directory -Path $InstallPath -ErrorAction Stop | Out-Null
        } catch {
            # UPDATED ERROR MESSAGE REFLECTING C: DRIVE
            Write-Error "Failed to create directory $InstallPath. Please check permissions and ensure C:\DiscordBots exists (or create it manually first)."
            exit 1
        }
    } else {
        Write-Host "Directory $InstallPath already exists. Files will be created/overwritten here."
    }

    # --- Change to the new directory ---
    try {
        Set-Location -Path $InstallPath -ErrorAction Stop
        Write-Host "Set working directory to $InstallPath"
    } catch {
        Write-Error "Failed to change directory to $InstallPath."
        exit 1
    }

    # --- Gather Remaining Bot Info ---
    Write-Host "`nPlease provide the following details for your bot."
    Write-Host "You can get your token from: https://discord.com/developers/applications"

    $BotToken = Read-Host -Prompt "Enter your Discord Bot Token (paste here)"
    $BotPrefix = Read-Host -Prompt "Enter your desired bot prefix (e.g., !)"

    # Basic validation
    if ([string]::IsNullOrWhiteSpace($BotToken) -or [string]::IsNullOrWhiteSpace($BotPrefix) -or [string]::IsNullOrWhiteSpace($BotInstanceName) -or [string]::IsNullOrWhiteSpace($ContainerName)) {
        Write-Error "All fields are required. Please re-run the script."
        exit 1
    }

    Write-Host "`nWriting configuration files in $InstallPath..."

    # --- Create .env file ---
    $envContent = @"
# --- Bot Configuration ---
# This file was auto-generated by deploy.ps1
BOT_TOKEN=$BotToken
BOT_PREFIX=$BotPrefix
BOT_INSTANCE_NAME=$BotInstanceName
"@
    $envContent | Out-File -FilePath ".env" -Encoding utf8
    Write-Host ".env file created."

    # --- Create docker-compose.yml file ---
    $composeContent = @"
version: "3.7"

services:
  red:
    image: registry.core.red-discordbot.com/red-discordbot/red-discordbot:latest
    container_name: $ContainerName 
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      RED_TOKEN: \${BOT_TOKEN}
      RED_PREFIX: \${BOT_PREFIX}
      RED_INSTANCE_NAME: \${BOT_INSTANCE_NAME}
      RED_DATA_PATH: "/data"
"@
    $composeContent | Out-File -FilePath "docker-compose.yml" -Encoding utf8
    Write-Host "docker-compose.yml file created."

    # --- Start the Docker Container ---
    Write-Host "`nStarting the Red-DiscordBot container '$ContainerName'..."
    Write-Host "This may take a moment if the image needs to be downloaded."
    Write-Host "Your bot's data will be stored in $InstallPath\data"

    try {
        docker-compose up -d
        Write-Host "`n--- Success! ---" -ForegroundColor Green
        Write-Host "Your bot '$BotInstanceName' is starting in the background."
        Write-Host ""
        Write-Host "To manage this bot, run commands from this directory: $InstallPath"
        Write-Host "  To see the bot's logs:   docker-compose logs -f"
        Write-Host "  To stop the bot:          docker-compose down"
    }
    catch {
        Write-Error "An error occurred while running 'docker-compose up'. Please check the output above."
        exit 1
    }
}

# --- Function to Install Node-RED (Visual Flow) ---
function Install-NodeRed {
    param (
        [string]$BasePath
    )

    Write-Host "`n--- 2. Installing Node-RED (Visual Flow Platform) ---"
    $InstanceName = Read-Host -Prompt "Enter a name for this Node-RED instance (e.g., my-node-red). This will be the folder name."
    $ContainerName = Read-Host -Prompt "Enter a unique name for the Docker container (e.g., nodered-docker)"

    # --- Construct and Create Installation Path ---
    $InstallPath = Join-Path -Path $BasePath -ChildPath $InstanceName

    if (-not (Test-Path -Path $InstallPath)) {
        Write-Host "Creating installation directory: $InstallPath"
        try {
            New-Item -ItemType Directory -Path $InstallPath -ErrorAction Stop | Out-Null
        } catch {
            # UPDATED ERROR MESSAGE REFLECTING C: DRIVE
            Write-Error "Failed to create directory $InstallPath. Please check permissions and ensure C:\DiscordBots exists (or create it manually first)."
            exit 1
        }
    } else {
        Write-Host "Directory $InstallPath already exists. Files will be created/overwritten here."
    }

    # --- Change to the new directory ---
    try {
        Set-Location -Path $InstallPath -ErrorAction Stop
        Write-Host "Set working directory to $InstallPath"
    } catch {
        Write-Error "Failed to change directory to $InstallPath."
        exit 1
    }

    Write-Host "`nWriting docker-compose.yml in $InstallPath..."

    # --- Create docker-compose.yml file ---
    # Note: We use host networking or ensure ports are unique if running multiple instances.
    # For simplicity in this script, we map 1880. If you run a second instance,
    # you must manually edit the docker-compose.yml to change "1880:1880" to something like "1881:1880".
    $composeContent = @"
version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: $ContainerName
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
"@
    $composeContent | Out-File -FilePath "docker-compose.yml" -Encoding utf8
    Write-Host "docker-compose.yml file created."

    # --- Start the Docker Container ---
    Write-Host "`nStarting the Node-RED container '$ContainerName'..."
    Write-Host "This may take a moment if the image needs to be downloaded."
    Write-Host "Your Node-RED data will be stored in $InstallPath\data"

    try {
        docker-compose up -d
        Write-Host "`n--- Success! ---" -ForegroundColor Green
        Write-Host "Node-RED is starting in the background."
        Write-Host ""
        Write-Host "--- IMPORTANT NEXT STEPS ---"
        Write-Host "1. Access the Node-RED editor in your browser at: http://localhost:1880"
        Write-Host "2. To create a Discord bot, open the top-right menu -> 'Manage Palette' -> 'Install'"
        Write-Host "3. Search for and install: node-red-contrib-discord-advanced"
        Write-Host ""
        Write-Host "To manage this instance, run commands from this directory: $InstallPath"
        Write-Host "  To see the logs:   docker-compose logs -f"
        Write-Host "  To stop:          docker-compose down"
    }
    catch {
        Write-Error "An error occurred while running 'docker-compose up'. Please check the output above."
        exit 1
    }
}


# --- Main Script ---

# 1. Check if Docker is running
try {
    docker ps -q | Out-Null
    Write-Host "Docker is running. Proceeding with setup..." -ForegroundColor Green
}
catch {
    Write-Error "Docker does not appear to be running. Please start Docker Desktop and re-run this script."
    exit 1
}

# 2. Define Base Path
# UPDATED BASE PATH TO C: DRIVE
$BasePath = "C:\DiscordBots"

# 3. Show Menu and Get Selection
Write-Host "`n===================================" -ForegroundColor Red
Write-Host "    🤖 Red-E Bot Multi-Deployer    " -ForegroundColor Yellow
Write-Host "===================================" -ForegroundColor Red
Write-Host "`nWhich type of bot would you like to install?"
Write-Host ""
Write-Host "  [1] Red-DiscordBot (Python Framework)"
Write-Host "  [2] Node-RED (Visual Flow Platform)"
Write-Host "  [Q] Quit"
Write-Host ""

$choice = Read-Host -Prompt "Enter your choice (1, 2, or Q)"

switch ($choice) {
    "1" {
        Install-RedBot -BasePath $BasePath
    }
    "2" {
        Install-NodeRed -BasePath $BasePath
    }
    "q" {
        Write-Host "Exiting script."
    }
    default {
        Write-Error "Invalid selection. Please run the script again and choose 1, 2, or Q."
    }
}
